spring:
  spring:
    rabbitmq:
      host: localhost
      port: 5672
      addresses: localhost:5672
      username: guest
      password: guest
      virtual-host: /
      dynamic: true
  application:
    name: usuarios
  datasource:
    url: jdbc:mysql://192.168.1.19:9999/db_usuarios?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
